do-install: Added --build-dir option

diff --git a/bin/do-install b/bin/do-install
--- a/bin/do-install
+++ b/bin/do-install
@@ -3,22 +3,26 @@
 # This little script runs the typical installation sequence for auto*
 # projects, installing them user-locally using stow
 
-project_name="`basename $PWD`"
-
 . ~/etc/sysinfo-common.sh
-
-getroot=""
-stow_args="--user"
-location="user-locally"
-prefix="$HOME/$sysdir/stow/$project_name"
-ask=yes
-reconf=false
 
 die() {
     echo "$@"
     exit 1
 }
 
+# Find out project name
+project_name="`basename $PWD`"
+
+# Default option values
+getroot=""
+stow_args="--user"
+location="user-locally"
+prefix="$HOME/$sysdir/stow/$project_name"
+ask=yes
+reconf=false
+builddir="."
+
+# Option processing
 done=false
 while ! [ -z "$1" ]; do
     case "$1" in
@@ -37,6 +41,17 @@ while ! [ -z "$1" ]; do
             shift
             reconf=true
             ;;
+        --build-dir)
+            shift
+            builddir="$1"
+            if [ "$builddir" = auto ]; then
+                builddir="_build"
+                if [ -n "$SYSTEM_NAME" ]; then
+                    builddir="$builddir-$SYSTEM_NAME"
+                fi
+            fi
+            shift
+            ;;
         --)
             shift
             done=true
@@ -49,7 +64,6 @@ while ! [ -z "$1" ]; do
 	break
     fi
 done
-
 
 if [ "$ask" = yes ]; then
     echo -n "Install $project_name $location? [y/n] "
@@ -67,11 +81,17 @@ if [ "$answer" = y ]; then
     if [ -d "$prefix" ]; then
 	do-stow $stow_args --purge "$project_name"
     fi
-    if [ -x configure ]; then
+    if [ -x "./configure" ]; then
 	set -e
+        src="."
+        if [ "$builddir" != "." ]; then
+            mkdir -p "$builddir"
+            cd "$builddir"
+            src=".."
+        fi
 	if [ "$reconf" = true ] || ! [ -f Makefile ]; then
-	    ./configure $configure_args "$@" || die "configure failed"
-	fi 
+	    "$src"/configure $configure_args "$@" || die "configure failed"
+	fi
 	(make && $getroot make install) || die "build/install failed"
     elif [ -x autogen.sh ]; then
 	(./autogen.sh $configure_args "$@" && make && $getroot make install ) \
@@ -79,8 +99,7 @@ if [ "$answer" = y ]; then
     elif [ -x setup.py ]; then
 	python setup.py build && $getroot python setup.py install --prefix="$prefix"
     else
-	echo "no installable project found here, aborting."
-	exit 1
+	die "no installable project found here, aborting."
     fi
     do-stow $stow_args "$project_name"
 fi
